#!/usr/bin/env perl
#
# stackcolllapse-phpspy.pl  collapse phpspy samples into single lines.
#
# Parses php samples generated by phpspy and outputs stacks as
# single lines, with methods separated by semicolons, and then a space and an
# occurrence count. For use with flamegraph.pl.
#
# USAGE: ./stackcollapse-phpspy.pl infile > outfile
#
# Example Input:
#   ...
#   0 sleep <internal>:-1
#   1 aaa /home/mlauter/profiling/sample.php:5
#   2 bbb /home/mlauter/profiling/sample.php:10
#   3 <main> /home/mlauter/profiling/sample.php:25
#   # trace_id = 0.0/1
#
#   0 sleep <internal>:-1
#   1 aaa /home/mlauter/profiling/sample.php:5
#   2 <main> /home/mlauter/profiling/sample.php:28
#   # trace_id = 1.0/1
#
#   0 sleep <internal>:-1
#   1 aaa /home/mlauter/profiling/sample.php:5
#   2 bbb /home/mlauter/profiling/sample.php:10
#   3 ccc /home/mlauter/profiling/sample.php:15
#   4 <main> /home/mlauter/profiling/sample.php:22
#   # trace_id = 2.0/1
#
#   ...
#
# A trace larger than phpspy's -b is written as several chunks, each ending in
# its own `# trace_id = <id>.<k>/<n>` record. In -P mode chunks of different
# traces may be interleaved in the stream; they are reassembled here by id.
#
# Example Output:
#   <main>;ccc;bbb;aaa 1
#   <main>;aaa 1
#   <main>;bbb;aaa;sleep 1
#
# To make a flamegraph:
# ./stackcollapse-phpspy.pl infile | ./vendor/flamegraph.pl > svg.out

use strict;
use warnings;

use Getopt::Long qw(:config gnu_getopt no_ignore_case);
use Encode qw(decode encode);

# parameters
my $help = 0;

sub usage {
    die <<USAGE_END;
USAGE: $0 [options] infile > outfile\n
    --h|help     # print this message
USAGE_END
}

GetOptions(
    'help|h' => \$help
) or usage();
usage() if $help;

# internals
my %stacks;
my @pending;      # funcs of the current, not-yet-terminated chunk
my %open;         # trace id => [ funcs accumulated so far ]
my %expect;       # trace id => next expected chunk index
my %bad;          # trace id => 1 once warned
my $seen_marker = 0;

while (defined(my $line = <>)) {
    chomp $line;

    # must be tested before the generic record filter below, which a marker
    # would otherwise match
    if ($line =~ m{^# trace_id = (\d+)\.(\d+)/(\d+)$}) {
        my ($id, $k, $m) = ($1, $2, $3);
        $seen_marker = 1;
        my $want = exists $expect{$id} ? $expect{$id} : 0;
        if ($k != $want) {
            warn "stackcollapse-phpspy: trace $id: expected chunk $want, got $k; discarding\n"
                unless $bad{$id};
            $bad{$id} = 1;
            delete $open{$id};
            delete $expect{$id};
            @pending = ();
            delete $bad{$id} if $k == $m - 1;
            next;
        }
        push @{$open{$id}}, @pending;
        @pending = ();
        $expect{$id} = $k + 1;
        if ($k == $m - 1) {
            $stacks{join(';', reverse @{$open{$id}})} += 1 if @{$open{$id}};
            delete $open{$id};
            delete $expect{$id};
            delete $bad{$id};
        }
        next;
    }

    next unless $line =~ /^(?:#|\d+) \S/;

    my ($depth, $func) = (split ' ', $line)[0,1];

    # decode the utf-8 bytes and make them into characters
    # and turn anything that's invalid into U+FFFD
    $func = decode("utf-8", $func);

    # Convert codepoints that break XML to ?
    $func =~ s/[\x01-\x08\x0B-\x0C\x0E-\x1F\x7F-\x84\x86-\x9F]/\x3F/g;

    # turn it back into a string
    $func = encode("utf-8", $func);

    # legacy (pre-trace_id) input: flush on each depth-0 frame
    if (!$seen_marker && $depth ne '#' && $depth == 0) {
        $stacks{join(';', reverse @pending)} += 1 if @pending;
        @pending = ();
    }

    push @pending, $func if $line =~ /^\d/;
}
# legacy input only: flush the tail. With markers, @pending and every
# incomplete %open entry are partial stacks and are discarded.
$stacks{join(';', reverse @pending)} += 1 if @pending && !$seen_marker;

while ( my ($k, $v) = each %stacks ) {
    print "$k $v\n";
}
