name: phpspy_test
on: [push, pull_request]
jobs:
  phpspy_test_job:
    runs-on: ubuntu-24.04
    env:
      TERM: xterm
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: deps
        run: |
          sudo apt-get install -y php8.3-cli
          echo "php_path:=/usr/bin/php8.3" | sudo tee config.mk
      - name: test
        run: make test
