name: phpspy_test

on:
  push:
    branches: [master]
  pull_request:

jobs:
  phpspy_test_job:
    strategy:
      matrix:
        runs_on: [ ubuntu-24.04, ubuntu-24.04-arm ]

    runs-on: ${{ matrix.runs_on }}

    env:
      TERM: xterm

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: deps
        run: |
          sudo apt-get install -y php8.3-cli
          echo "php_cmd:=/usr/bin/php8.3" | sudo tee config.mk

      - name: test
        run: make test
